project:
  type: website
  output-dir: docs
website:
  title: "myquarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reference/index.qmd
        text: Reference
      - href: articles/index.qmd
        text: Articles
      - href: news/index.qmd
        text: News
format:
  html:
    theme: default
    toc: true
